server:
  port: 9090

spring:
  application:
    name: microservice-mailchimp
  datasource:
    url: ${CRM_URL}
    username: ${CRM_USERNAME}
    password: ${CRM_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  config:
    import: ${CONFIGSERVER_HOST}
mailchimp:
  api:
    key: ${MAILCHIMP_API_KEY}
    base-url: ${MAILCHIMP_API_URL}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}